build:
    docker compose build

start *args:
    docker compose --env-file .env up --build {{ args }}

stop:
    docker compose --env-file .env down

clean:
    docker compose --env-file .env down --volumes --rmi all
