name: Build and Push Multi-Architecture Image to GHCR

on:
  push:
    tags:
      - 'v*'
    paths:
      - '*.go'
      - 'go.*'
      - 'docker/Dockerfile'
      - 'docker/entry.sh'

env:
  PLATFORMS: linux/amd64,linux/arm64
  GHCR_IMAGE_URL: ghcr.io/${{ github.actor }}/tailscale-coredns
  TARGETARCH: ${{ env.TARGETARCH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: tags
        run: |
          TAGS="${{ env.GHCR_IMAGE_URL }}:latest"
          if [ "${{ github.ref_type }}" = "tag" ]; then
            TAGS="$TAGS,${{ env.GHCR_IMAGE_URL }}:${{ github.ref_name }}"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            TARGETARCH=${{ env.TARGETARCH }}
